-- Migration 002: skill_drafts table
-- Supports the document-to-skill feature: upload PDF/PPTX/DOCX → LLM draft → review → save as skill
-- Idempotent: safe to run multiple times

CREATE TABLE IF NOT EXISTS taxlegal.skill_drafts (
    id                  SERIAL PRIMARY KEY,
    filename            TEXT NOT NULL,
    original_size_bytes INTEGER,
    extracted_text      TEXT,                          -- first 50k chars of extracted document text
    topic_slug          TEXT,                          -- auto-detected topic: pit, vat, customs, ...
    topic_label         TEXT,                          -- human-readable: "Thuế TNCN", "VAT", ...
    draft_content       TEXT,                          -- editable skill markdown generated by LLM
    suggested_slug      TEXT,                          -- LLM-suggested slug for the skill
    status              TEXT DEFAULT 'draft',          -- draft | saved | discarded
    saved_skill_id      INTEGER REFERENCES taxlegal.skills(id) ON DELETE SET NULL,
    created_by          INTEGER REFERENCES taxlegal.users(id) ON DELETE SET NULL,
    created_at          TIMESTAMP DEFAULT NOW(),
    updated_at          TIMESTAMP DEFAULT NOW()
);

-- Index for user-specific draft listings
CREATE INDEX IF NOT EXISTS ix_skill_drafts_created_by ON taxlegal.skill_drafts(created_by);

-- Index for reverse lineage lookup (skill → originating draft)
CREATE INDEX IF NOT EXISTS ix_skill_drafts_saved_skill_id ON taxlegal.skill_drafts(saved_skill_id);

-- Index for status-filtered listings
CREATE INDEX IF NOT EXISTS ix_skill_drafts_status ON taxlegal.skill_drafts(status);

COMMENT ON TABLE taxlegal.skill_drafts IS
  'Staging table for document-to-skill workflow: tracks uploaded documents, extracted text, LLM-generated draft skill content, and final disposition (saved or discarded).';
